spring:
    data:
        mongodb:
            authentication-database: admin
            repositories:
                enabled: true
            host: 0.0.0.0
            port: 27017
            database: cloud_fornecedor
            username: root
            password: root